import rootConfig from '../../eslint.config.mjs';

const transitionalLegacyPureMoveFiles = [
  'src/ColorModeSwitcher.tsx',
  'src/components/academics/AcademicExperience.tsx',
  'src/components/academics/Degree.ts',
  'src/components/academics/Degrees.tsx',
  'src/components/containers/TitledSection.tsx',
  'src/components/home/Experience.tsx',
  'src/components/home/TechnicalSkillsSection.tsx',
  'src/components/icons/ArizonaWildcatIcon.tsx',
  'src/components/icons/CSharpIcon.tsx',
  'src/components/icons/IuTridentIcon.tsx',
  'src/components/icons/JavaIcon.tsx',
  'src/components/icons/KotlinIcon.tsx',
  'src/components/icons/MicrosoftIcon.tsx',
  'src/components/icons/ReactIcon.tsx',
  'src/components/nav/Footer.tsx',
  'src/components/projects/ProjectPage.tsx',
  'src/components/projects/fitness/FitnessUtils.tsx',
  'src/components/projects/fitness/ViewActivityByWeek.tsx',
  'src/components/projects/fitness/ViewToursByMonth.tsx',
  'src/components/projects/spotify/TrackAttribute.ts',
  'src/components/projects/spotify/playlist_generator/CreateSpotifyPlaylistModal.tsx',
  'src/components/projects/spotify/playlist_generator/SeedView.tsx',
  'src/components/projects/spotify/playlist_generator/SetTrackAttributeValueAndTypeComponent.tsx',
  'src/components/projects/spotify/playlist_generator/SpotifyGenerateAndShowPlaylistRecommendationsComponent.tsx',
  'src/components/projects/spotify/playlist_generator/SpotifyTrackAttributeSelectorComponent.tsx',
  'src/components/projects/spotify/views/SpotifyArtist.tsx',
  'src/components/projects/spotify/views/SpotifyEpisode.tsx',
  'src/components/projects/spotify/views/SpotifyPlaylist.tsx',
  'src/components/projects/spotify/views/SpotifyTrack.tsx',
  'src/components/utils/DashedSpanWithTooltip.tsx',
  'src/components/utils/NextUtils.ts',
  'src/components/utils/SpotifyApiPaginationHelper.ts',
  'src/components/utils/SpotifyTypes.ts',
  'src/components/utils/StringUtils.tsx',
  'src/components/utils/SwrUtils.ts',
  'src/components/utils/useColorModeColor.ts',
  'src/components/utils/useData.ts',
  'src/components/utils/useKomootData.ts',
  'src/components/utils/useNoShowBeforeRender.ts',
  'src/routes/projects/calculator.tsx',
  'src/routes/projects/spotify/callback.tsx',
  'src/react-console-emulator.d.ts',
  'src/spotify-utils/auth/SpotifyLogoutButton.tsx',
  'src/theme.ts',
];

export default [
  ...rootConfig,
  {
    name: 'web/transitional-legacy-pure-moves',
    files: transitionalLegacyPureMoveFiles,
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-base-to-string': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-floating-promises': 'off',
      '@typescript-eslint/no-misused-promises': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-unsafe-argument': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-unsafe-function-type': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-return': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      'no-unsafe-optional-chaining': 'off',
    },
  },
];
